services:
  - type: web
    name: supplier-risk-api
    runtime: python
    pythonVersion: 3.12
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
