

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
    env_file:
      - ../.env
    working_dir: /app
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ../frontend:/app
    env_file:
      - ../.env
    depends_on:
      - backend
    restart: unless-stopped
